name: CI

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master]

jobs:
    ci:
        uses: nuniesmith/fks_actions/.github/workflows/ci-infra-service.yml@main
        with:
            service_name: nginx
            service_port: 80
            validate_config: false
        secrets:
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
